version: '3.8'

services:
  nuxtapp:
    container_name: bullaska
    build:
      context: .
      dockerfile: Dockerfile

    image: bullaska:1.0.0

    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
