version: '3.8'

services:
  bullaska:
    container_name: bullaska
    build:
      context: .
    pull_policy: build
    image: bullaska:latest
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
