version: '3.8'

services:
  bullaska:
    container_name: bullaska
    build: .
    image: bullaska:1.2
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
