<template>
  <div class="font-work-sans text-xl">
    <br />
    <p class="px-6 sm:px-24">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed ornare erat. Praesent quis euismod nisl. Mauris sit amet rutrum urna. Donec id purus ullamcorper, consectetur mi eu, consequat eros. Nullam faucibus consectetur velit, vel posuere nulla elementum accumsan. Donec ultricies ex tellus, vitae volutpat odio pulvinar nec. Nulla dictum varius ipsum, nec auctor ipsum placerat vitae.
      Suspendisse ultricies leo risus. Aliquam erat volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque ut maximus elit. Vivamus ac congue elit, sit amet molestie tellus. In vitae aliquet tortor. Proin metus augue, posuere non dapibus a, ultricies ac mi. Ut arcu sapien, feugiat et urna eget, blandit aliquet quam. Suspendisse sit amet molestie turpis. Nulla eu ex mollis, dapibus metus sit amet, tempus sem. Proin enim augue, finibus quis lorem vel, faucibus porta tellus. Nam tincidunt posuere volutpat.
      Nam accumsan rutrum orci ac consectetur. Morbi ornare eros vitae imperdiet ornare. Proin urna nisl, ultricies vitae malesuada eu, malesuada sed dui. Nullam et lacinia metus. Phasellus sodales rutrum tellus non faucibus. Nunc lacinia gravida arcu eu lacinia. Praesent lacinia eros dolor, ut sodales mi convallis eget. Vivamus at nibh vehicula mi sodales pharetra at sit amet sem. Suspendisse interdum massa placerat massa ultrices, et dictum libero volutpat. Morbi ornare urna ac tempor placerat. Aliquam ultrices nisi nulla, id blandit elit ultrices in. Nam et pellentesque enim, vel dictum felis. Sed at mi volutpat, finibus orci ut, sodales tortor. Pellentesque tristique metus id nisl aliquam, sit amet pharetra neque molestie. Suspendisse felis mauris, maximus id sapien eget, porta fringilla dolor. Ut at nisi et sem cursus mollis nec non mi.
      Suspendisse ut mi sit amet justo finibus bibendum in non purus. Pellentesque non dolor sapien. Maecenas nibh nisi, pellentesque ac nibh eu, condimentum mattis leo. Praesent non scelerisque eros, a scelerisque lectus. Sed feugiat neque nec orci ornare laoreet. Pellentesque sit amet orci non nisi pretium semper et vel metus. Quisque lobortis vulputate quam. Donec mollis, dui eu placerat tincidunt, mi odio porttitor ante, quis ornare metus risus quis risus. Ut tempus congue mi, vitae elementum lorem pulvinar a. Etiam gravida aliquet nisi quis commodo. Pellentesque ultricies velit tellus, sit amet pretium ligula vestibulum nec. Curabitur sed tincidunt enim, ac facilisis arcu. Donec eu congue augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
      Quisque lobortis nisl at felis tempus, a finibus metus imperdiet.
    </p>
  </div>
</template>